name: huerto_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  google_sign_in:
  flutter_auth_buttons:
  hasura_connect: ^0.0.8
  dio: ^2.1.13
  rxdart: ^0.22.1+1
  bloc_pattern: ^2.2.3
  email_validator: '^1.0.0'
  toast: ^0.1.5
  line_icons: ^0.2.0
  get_it: ^4.0.1
  firebase_messaging: ^6.0.16
  flutter_contact: ^0.6.1 
  permission_handler: ^5.0.1+1
  rflutter_alert: ^1.0.3
  http: ^0.12.2
  flutter_beautiful_popup: ^1.5.0
  url_launcher: ^5.5.0
  flutter_open_whatsapp: ^0.1.2
  cloud_firestore: ^0.12.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

    
     
